CREATE TABLE IF NOT EXISTS Run (
  id INT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  startedOn TIMESTAMP NOT NULL,
  completedOn TIMESTAMP NOT NULL,
  miles INT NOT NULL,
  location VARCHAR(10) NOT NULL,
  PRIMARY KEY (id)
);